### ISSUE TITLE
VOC训练问题

### ISSUE THREAD

**Issue by snovire** [yeyupiaoling/PP-YOLOE#1]
您好，使用VOC数据按照教程训练时，出现ValueError: not enough values to unpack (expected 2, got 1)问题，请问怎么解决呢
![微信截图_20200901220108](https://user-images.githubusercontent.com/49724561/91860835-b8583d80-ec9e-11ea-8d71-fc0d970a83bd.png)

**Comment by yeyupiaoling** [comment]
@snovire 这个错误发生读取数据列表的时候，你查看一下训练数据列表和测试数据列表是否都正确生成了

主要格式如下，中间是空格隔开的
```
images/00019.jpg annotation/00019.xml
images/00039.jpg annotation/00039.xml
images/00059.jpg annotation/00059.xml
images/00081.jpg annotation/00081.xml
images/00101.jpg annotation/00101.xml
```

**Comment by yeyupiaoling** [comment]
没有问题我就关闭了
