### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yangkang121** [yeyupiaoling/PP-YOLOE#10]
怎么不能加载coco的官方预训练模型

**Comment by yeyupiaoling** [comment]
可以啊

**Comment by yangkang121** [comment]
那我根据您的readme进行调试,运行export_model.py文件时,显示AssertionError: 模型参数文件不存在！

**Comment by yangkang121** [comment]
请问COCO的预训练模型怎么导出?

**Comment by yeyupiaoling** [comment]
会自动下载的。具体什么错误？

**Comment by yangkang121** [comment]
Traceback (most recent call last):
  File "D:/PythonTest/PP-YOLOE/export_model.py", line 57, in <module>
    export_model()
  File "D:/PythonTest/PP-YOLOE/export_model.py", line 39, in export_model
    assert os.path.exists(os.path.join(args.resume_model, 'model.pdparams')), "模型参数文件不存在！"
AssertionError: 模型参数文件不存在！

**Comment by yeyupiaoling** [comment]
你参数是怎么设定的？

**Comment by yeyupiaoling** [comment]
看文档说明。可以自动下载官方模型的。

**Comment by yangkang121** [comment]
python export_model.py --resume_model=None我就运行的这句话,没干别的....

**Comment by yeyupiaoling** [comment]
应该有个下载过程的那个下载过程成功吗？

**Comment by yangkang121** [comment]
没有下载过程,我打上python export_model.py --resume_model=None,过一会就报上面那个错误了.

**Comment by yeyupiaoling** [comment]
根据错误提示，你那个并没有设置为None

**Comment by yangkang121** [comment]
可我就是从github上拷下您的代码来,按照您的Readme来的,怎么会出错误呢?

**Comment by yangkang121** [comment]
您现在在自己的电脑上跑可以正常运行嘛?请问

**Comment by yeyupiaoling** [comment]
你直接在源码里面设置为None

**Comment by yangkang121** [comment]
这个label_list.txt为什么是空的呀?请问

**Comment by yangkang121** [comment]
郁闷了,每走一步都要报错.....

**Comment by yeyupiaoling** [comment]
有的。应该你是删除了。你重新复制一份就可以了。

**Comment by yangkang121** [comment]
![1664362866(1)](https://user-images.githubusercontent.com/46737132/192762874-8fa76983-fcd4-4b79-ac14-fa5093ccbd39.png)
我想问一下您的export_model.py里的那个代码是这样子嘛?

**Comment by yeyupiaoling** [comment]
嗯

**Comment by yangkang121** [comment]
![image](https://user-images.githubusercontent.com/46737132/192764083-a27b0c22-ab11-47cb-ab3f-0d352a7da995.png)
请问nin您所说的准备训练数据train.json和评估数据eval.json是要自己准备嘛?还是您这里面就有?

**Comment by yeyupiaoling** [comment]
要自己准备，你自己的数据集。
