### ISSUE TITLE
oriented object detection

### ISSUE THREAD

**Issue by pangyanhua** [yeyupiaoling/PP-YOLOE#13]
how can I implement OBB with your pp-yoloe? I can not find a solution about it. If you have any advice for this please tell me, thank you!

**Comment by yeyupiaoling** [comment]
这个目前是不行的，因为输入的数据是固定的。

**Comment by yeyupiaoling** [comment]
看这个：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rotate/ppyoloe_r

**Comment by pangyanhua** [comment]
> 看这个：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rotate/ppyoloe_r
太感谢了！！！
