### ISSUE TITLE
epoch改为200回合后，在训练到100回合时报错

### ISSUE THREAD

**Issue by Max-Zhan** [yeyupiaoling/PP-YOLOE#17]
请问各位大佬这是怎么回事嘞，不胜感激！
报错如下：
ValueError: (InvalidArgument) The 3-th dimension of input tensor is expected to be equal with the 3-th dimension of output tensor 2 or 1, but recieved 0. (at /paddle/paddle/phi/kernels/funcs/broadcast_function.h:76)
  [operator < elementwise_min > error]

前面的报错：
 File "train.py", line 53, in <module>
    pretrained_model=args.pretrained_model)
  File "/root/autodl-tmp/PP-YOLOE/ppyoloe/trainer.py", line 300, in train
    self.__train_epoch(max_epoch=num_epoch, epoch_id=epoch_id, log_interval=log_interval, local_rank=local_rank, writer=writer)
  File "/root/autodl-tmp/PP-YOLOE/ppyoloe/trainer.py", line 204, in __train_epoch
    output = self.model(data)

**Comment by yeyupiaoling** [comment]
@Max-Zhan 感谢像是数据有问题
