### ISSUE TITLE
2020-10-21 22:58:00,947-WARNING: Found an invalid bbox in annotations: xml_file: dataset/annotation/001113.xml, x1: 3765.0, y1: 1851.0, x2: 3765.0, y2: 1871.0.

### ISSUE THREAD

**Issue by whisperLiang** [yeyupiaoling/PP-YOLOE#3]
2020-10-21 22:58:00,947-WARNING: Found an invalid bbox in annotations: xml_file: dataset/annotation/001113.xml, x1: 3765.0, y1: 1851.0, x2: 3765.0, y2: 1871.0.

**Comment by yeyupiaoling** [comment]
@whisperLiang 你查一下`dataset/annotation/001113.xml`这个标注文件有没有什么问题

**Comment by whisperLiang** [comment]
嗯，谢谢，就是一个背景的标记和图片的边界大小一样，然后报错了，我改成了<=就好了，还有一个问题就是我的模型训练一段时间之后那样信息都变成了nan这是为什么呢？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "夜雨飘零"<notifications@github.com&gt;; 
发送时间: 2020年10月25日(星期天) 中午11:52
收件人: "yeyupiaoling/PP-YOLO"<PP-YOLO@noreply.github.com&gt;; 
抄送: "听不清的耳语"<1851438730@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yeyupiaoling/PP-YOLO] 2020-10-21 22:58:00,947-WARNING: Found an invalid bbox in annotations: xml_file: dataset/annotation/001113.xml, x1: 3765.0, y1: 1851.0, x2: 3765.0, y2: 1871.0. (#3)





 
@whisperLiang 你查一下dataset/annotation/001113.xml这个标注文件有没有什么问题

**Comment by yeyupiaoling** [comment]
@whisperLiang 是不是你的batch size设置小了，这样的话学习率也要改小

**Comment by yumeng88** [comment]
数据越界，不影响训练
