### ISSUE TITLE
运行train.py报错

### ISSUE THREAD

**Issue by zhong110020** [yeyupiaoling/PP-YOLOE#7]
![image](https://user-images.githubusercontent.com/23289919/124713581-4f32fd80-df33-11eb-9288-7152ad99cfc7.png)

**Comment by yeyupiaoling** [comment]
@zhong110020 噢，忘记官方提供的，跟我本地的有点不一样，等下，我修改这个问题。

**Comment by yeyupiaoling** [comment]
@zhong110020 修复了，你拉下最新代码
