### ISSUE TITLE
多卡训练该如何配置

### ISSUE THREAD

**Issue by ponycloud235** [yeyupiaoling/PP-YOLOE#9]
`
export CUDA_VISIBLE_DEVICES=0,1
python3 -m paddle.distributed.launch --gpus 0,1 train.py  --eval`

执行上面的命令报错，麻烦看看，该如何调整支持多卡
![image](https://user-images.githubusercontent.com/2733701/140287692-ee0b346c-2660-4cc8-9a5e-28d6962b1440.png)

**Comment by yeyupiaoling** [comment]
你有两张显卡吗？都正常吗？

**Comment by ponycloud235** [comment]
嗯，有两张，都正常的，也装了nccl2
![image](https://user-images.githubusercontent.com/2733701/140314601-d168cf4e-7738-46de-9554-a2a208c512a8.png)

**Comment by yeyupiaoling** [comment]
我也看不出是什么原因
